FROM openjdk:8-jdk-alpine
RUN apk --no-cache add curl
RUN apk --no-cache add bash
RUN apk --no-cache add git
VOLUME /tmp
COPY target/postgresql-0.0.1-SNAPSHOT.jar app/app.jar
RUN cd app/ && git clone https://github.com/vishnubob/wait-for-it.git
RUN chmod +x app/wait-for-it.sh
COPY docker_tools/start.sh /start.sh
RUN chmod +x start.sh
HEALTHCHECK --interval=5s --timeout=3s CMD curl --fail http://localhost:8081/actuator/health || exit 1
ENV JAVA_OPTS=""
ENTRYPOINT [ "bin/sh", "start.sh" ]


