version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=coursedb
    restart: unless-stopped
  discovery:
    build: discovery/.
    image: developer.okta.com/microservice-docker-discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  config:
    build: config/.
    image: developer.okta.com/microservice-docker-config:0.0.1-SNAPSHOT
    volumes:
      - ./config-data:/var/config-data
    # Define profile native to start local, delete Dspring.profiles.active to start with git
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - discovery
    ports:
      - 8888:8888
  school-ui:
    image: developer.okta.com/microservice-docker-school-ui:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
      - discovery
      - config
      - db
    ports:
      - 8080:8080
  postgresql:
    image: developer.okta.com/microservice-docker-postgresql:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.profiles.active=docker
    restart: on-failure
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - discovery
      - config
      - db
  gateway:
    image: developer.okta.com/microservice-docker-gateway:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.profiles.active=docker
    restart: on-failure
    expose:
      - 5555
    ports:
      - 5555:5555
    depends_on:
      - discovery
      - config
      - db
volumes:
  postgres-data:
